(function(){
'use strict';
var core=window.PenKidsCore;if(!core)return;
var panel=document.getElementById('syncPanel'),roomInput=document.getElementById('syncRoomInput'),adminEl=document.getElementById('syncAdminMode'),codeView=document.getElementById('syncCodeView'),linkInput=document.getElementById('syncLinkInput'),statusEl=document.getElementById('syncStatus'),usersEl=document.getElementById('syncUsers'),compatEl=document.getElementById('syncCompat'),badge=document.getElementById('badgeSync');
var peer=null,hostConn=null,conns=[],role='none',room='',adminMode='creator',connected=false,loading=false,waiters=[],token='u'+Math.random().toString(36).substr(2,8),lastStrokeSend=0,lastStrokeSig='',applying=false;
function esc(s){return(''+(s||'')).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function clean(v){return(''+(v||'')).toUpperCase().replace(/[^A-Z0-9_-]/g,'').substr(0,16)}
function randomCode(){var c='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',s='',i;for(i=0;i<6;i++)s+=c.charAt(Math.floor(Math.random()*c.length));return s}
function hostId(c){return'pkdraw-'+clean(c).toLowerCase()}
function baseUrl(){if(/^https?:$/i.test(location.protocol))return location.href.split('#')[0].split('?')[0];return'https://raw.githack.com/saddamalkhatabi/kamaran.github.io/master/pen/index.html'}
function shareUrl(){return baseUrl()+'?room='+encodeURIComponent(room)}
function setStatus(s){statusEl.innerHTML=esc(s);badge.innerHTML='المزامنة: '+esc(s)}
function userName(){return(core.getUserName&&core.getUserName())||'مستخدم'}
function canAdmin(){return role==='host'||(connected&&adminMode==='all')}
function requireAdmin(){if(!connected||canAdmin())return true;if(core.setStatus)core.setStatus('التحكم بالشاشة للمنشئ فقط، ويمكنك الاستمرار في الرسم');return false}
function updatePermissions(){var locked=connected&&!canAdmin(),ids=['clearBtn','undoBtn','prevBtn','nextBtn','showAllBtn','itemSelect','assistBtn','quickClearBtn','quickPrevBtn','quickNextBtn','quickModeSelect','quickItemSelect','quickShowAllBtn'],i,e,bs=document.getElementById('tabs').getElementsByTagName('button');for(i=0;i<ids.length;i++){e=document.getElementById(ids[i]);if(e)e.disabled=locked}for(i=0;i<bs.length;i++)bs[i].disabled=locked;adminEl.disabled=(connected&&role!=='host')}
function updateUi(){codeView.innerHTML=room?esc(room):'—';linkInput.value=room?shareUrl():'';adminEl.value=adminMode;updatePermissions()}
function renderUsers(a){var i,out=[];if(!a||!a.length){usersEl.innerHTML='لا يوجد مشاركون بعد.';return}for(i=0;i<a.length;i++)out.push('👤 '+esc(a[i].name||'مستخدم')+(a[i].role==='host'?' <b>(المنشئ)</b>':''));usersEl.innerHTML=out.join('<br>')}
function presence(){var a=[{name:userName(),role:'host',id:peer?peer.id:'host'}],i,c;for(i=0;i<conns.length;i++){c=conns[i];if(c&&c.open)a.push({name:(c.metadata&&c.metadata.name)||'مستخدم',role:'guest',id:c.peer})}return a}
function sendRaw(msg,except){var i,c;for(i=0;i<conns.length;i++){c=conns[i];if(c&&c.open&&c!==except)try{c.send(msg)}catch(e){}}}
function send(msg){if(!connected)return false;msg=msg||{};msg.fromName=userName();msg.fromToken=token;if(role==='host'){sendRaw(msg,null);return true}if(hostConn&&hostConn.open)try{hostConn.send(msg);return true}catch(e){}return false}
function broadcastPresence(){if(role!=='host')return;var a=presence();renderUsers(a);sendRaw({type:'presence',users:a,adminMode:adminMode},null)}
function loadPeer(cb){if(window.Peer){cb(true);return}waiters.push(cb);if(loading)return;loading=true;var urls=['https://cdnjs.cloudflare.com/ajax/libs/peerjs/1.5.5/peerjs.min.js','https://cdn.jsdelivr.net/npm/peerjs@1.5.5/dist/peerjs.min.js','https://unpkg.com/peerjs@1.5.5/dist/peerjs.min.js'],i=0;function done(ok){var q=waiters.slice(0),j;waiters=[];loading=false;for(j=0;j<q.length;j++)try{q[j](ok)}catch(e){}}function next(){if(window.Peer){done(true);return}if(i>=urls.length){done(false);return}var s=document.createElement('script');s.src=urls[i++];s.async=true;s.onload=function(){window.Peer?done(true):next()};s.onerror=next;document.getElementsByTagName('head')[0].appendChild(s)}next()}
function support(){var rtc=!!(window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection);compatEl.innerHTML=rtc?'هذا الجهاز يدعم WebRTC مبدئياً. المزامنة تستخدم PeerJS Cloud للإشارة، ثم تنتقل بيانات الرسم بين الأجهزة عبر WebRTC المشفر.':'هذا المتصفح لا يظهر دعم WebRTC. سيبقى الرسم المحلي يعمل، لكن المزامنة البعيدة قد لا تعمل على هذا الجهاز.';return rtc}
function closeAll(){var i;for(i=0;i<conns.length;i++)try{conns[i].close()}catch(e){}conns=[];try{if(hostConn)hostConn.close()}catch(e){}hostConn=null;try{if(peer)peer.destroy()}catch(e){}peer=null;role='none';connected=false;room='';setStatus('غير متصل');renderUsers([]);updateUi()}
function ensureId(st){if(!st)return'';if(!st._syncId)st._syncId=token+'-'+(new Date().getTime())+'-'+Math.random().toString(36).substr(2,5);if(!st._syncOwner)st._syncOwner=token;return st._syncId}
function serializeStroke(st){if(!st||!st.length)return null;ensureId(st);var b=core.getBoard(),r=b.getBoundingClientRect(),w=r.width||1,h=r.height||1,p=[],i,x;for(i=0;i<st.length;i++){x=st[i];p.push({x:x.x/w,y:x.y/h,c:x.c||'#111111'})}return{id:st._syncId,owner:st._syncOwner||token,points:p}}
function serializeAll(){var a=[],s=core.getStrokes(),i,x;for(i=0;i<s.length;i++){x=serializeStroke(s[i]);if(x)a.push(x)}return a}
function findStroke(id){var s=core.getStrokes(),i;for(i=0;i<s.length;i++)if(s[i]&&s[i]._syncId===id)return i;return-1}
function makeStroke(x){var b=core.getBoard(),r=b.getBoundingClientRect(),w=r.width||1,h=r.height||1,st=[],i,p;for(i=0;i<(x.points||[]).length;i++){p=x.points[i];st.push({x:p.x*w,y:p.y*h,c:p.c||'#111111'})}st._syncId=x.id;st._syncOwner=x.owner||'remote';return st}
function applyStroke(x){if(!x||!x.id)return;var s=core.getStrokes(),i=findStroke(x.id),st=makeStroke(x);if(i>=0)s[i]=st;else s.push(st);core.redraw()}
function applyAll(a){var s=core.getStrokes(),i;s.length=0;for(i=0;i<(a||[]).length;i++)s.push(makeStroke(a[i]));core.redraw()}
function screenState(){return core.getScreen?core.getScreen():{}}
function applyMessage(m){if(!m||!m.type)return;applying=true;try{if(m.type==='stroke')applyStroke(m.stroke);else if(m.type==='allstrokes')applyAll(m.strokes||[]);else if(m.type==='clear')core.clear();else if(m.type==='screen'&&core.applyScreen){core.applyScreen(m.state||{});updatePermissions();}else if(m.type==='presence'){adminMode=m.adminMode==='all'?'all':'creator';renderUsers(m.users||[]);updateUi()}else if(m.type==='permissions'){adminMode=m.adminMode==='all'?'all':'creator';updateUi();setStatus(adminMode==='all'?'الجميع لديهم صلاحية التحكم':'التحكم بالشاشة للمنشئ فقط')}else if(m.type==='welcome'){adminMode=m.adminMode==='all'?'all':'creator';if(core.applyScreen)core.applyScreen(m.screen||{});applyAll(m.strokes||[]);renderUsers(m.users||[]);connected=true;setStatus('متصل بالغرفة '+room);updateUi()}}finally{applying=false}}
function handleGuest(conn,m){if(!m||!m.type)return;var ok=(m.type==='stroke');if(adminMode==='all'&&(m.type==='screen'||m.type==='clear'||m.type==='allstrokes'))ok=true;if(!ok)return;applyMessage(m);sendRaw(m,conn)}
function bindGuest(conn){conns.push(conn);conn.on('open',function(){connected=true;var a=presence();try{conn.send({type:'welcome',adminMode:adminMode,screen:screenState(),strokes:serializeAll(),users:a})}catch(e){}broadcastPresence();setStatus('الجلسة تعمل - '+room)});conn.on('data',function(m){handleGuest(conn,m)});conn.on('close',function(){for(var i=conns.length-1;i>=0;i--)if(conns[i]===conn)conns.splice(i,1);broadcastPresence()});conn.on('error',broadcastPresence)}
function createRoom(){var c=clean(roomInput.value);if(!c){c=randomCode();roomInput.value=c}closeAll();room=c;adminMode=adminEl.value==='all'?'all':'creator';role='host';updateUi();setStatus('جارٍ إنشاء الجلسة...');loadPeer(function(ok){if(!ok){role='none';setStatus('تعذر تحميل مكتبة الاتصال. تحقق من الإنترنت ثم أعد المحاولة.');return}try{peer=new Peer(hostId(c),{debug:1});peer.on('open',function(id){connected=true;token=id||token;setStatus('الجلسة جاهزة - شارك الرمز '+c);renderUsers(presence());updateUi()});peer.on('connection',bindGuest);peer.on('error',function(err){var t=err&&err.type||'';setStatus(t==='unavailable-id'?'الرمز مستخدم الآن. اختر رمزاً آخر.':'خطأ اتصال: '+t)});peer.on('disconnected',function(){setStatus('انقطع خادم الإشارة، والاتصالات المفتوحة قد تستمر')})}catch(e){setStatus('تعذر إنشاء الجلسة: '+e.message)}})}
function joinRoom(){var c=clean(roomInput.value);if(!c){setStatus('أدخل رمز المشاركة أولاً');return}closeAll();room=c;role='guest';updateUi();setStatus('جارٍ الدخول إلى '+c+' ...');loadPeer(function(ok){if(!ok){role='none';setStatus('تعذر تحميل مكتبة الاتصال. تحقق من الإنترنت ثم أعد المحاولة.');return}try{peer=new Peer(undefined,{debug:1});peer.on('open',function(id){token=id||token;hostConn=peer.connect(hostId(c),{serialization:'json',reliable:true,metadata:{name:userName()}});hostConn.on('open',function(){connected=true;setStatus('تم الاتصال، جارٍ استلام اللوحة...');updateUi()});hostConn.on('data',applyMessage);hostConn.on('close',function(){connected=false;setStatus('انتهت الجلسة أو خرج المنشئ');updatePermissions()});hostConn.on('error',function(){setStatus('تعذر الاتصال بالمنشئ')})});peer.on('error',function(err){setStatus('خطأ اتصال: '+(err&&err.type||'غير معروف'))})}catch(e){setStatus('تعذر الدخول: '+e.message)}})}
function copyText(t){try{if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(t);return true}}catch(e){}try{linkInput.value=t;linkInput.focus();linkInput.select();return document.execCommand('copy')}catch(e){return false}}
function copyCode(){if(!room){setStatus('لا يوجد رمز بعد');return}copyText(room);setStatus('تم نسخ الرمز '+room)}
function share(){if(!room){setStatus('أنشئ جلسة أولاً');return}var u=shareUrl();linkInput.value=u;try{if(navigator.share){navigator.share({title:'لوحة الطفل - جلسة رسم مشتركة',text:'انضم إلى جلسة الرسم بالرمز '+room,url:u});return}}catch(e){}copyText(u);setStatus('تم نسخ رابط المشاركة')}
function openPanel(){panel.style.display='block';support();if(!roomInput.value)roomInput.value=room||randomCode();updateUi()}
function closePanel(){panel.style.display='none'}
function localStroke(finalSend){if(!connected||applying)return;var a=core.getStrokes();if(!a||!a.length)return;var st=a[a.length-1],x=serializeStroke(st);if(!x)return;var sig=x.id+':'+x.points.length;if(!finalSend&&sig===lastStrokeSig)return;lastStrokeSig=sig;send({type:'stroke',stroke:x})}
function localScreen(clear){if(!connected||applying||!canAdmin())return;var st=screenState();st.clearDrawing=!!clear;send({type:'screen',state:st})}
function localClear(){if(!connected||applying||!canAdmin())return;send({type:'clear'})}
function localUndo(){if(!connected||applying||!canAdmin())return;send({type:'allstrokes',strokes:serializeAll()})}
function eventTarget(e){return e&&e.target?e.target:null}
function onUiEvent(e){var t=eventTarget(e),id=t&&t.id||'',cls=t&&t.className||'';setTimeout(function(){if(applying||!connected)return;if(id==='clearBtn'||id==='quickClearBtn'){localClear();return}if(id==='undoBtn'){localUndo();return}if(id==='prevBtn'||id==='nextBtn'||id==='quickPrevBtn'||id==='quickNextBtn'||id==='itemSelect'||id==='quickModeSelect'||id==='quickItemSelect'||(typeof cls==='string'&&cls.indexOf('tab')>=0)||(typeof cls==='string'&&cls.indexOf('pick')>=0)){localScreen(true);return}if(id==='assistBtn')localScreen(false)},0)}
var b=core.getBoard();b.addEventListener('touchmove',function(){if(!connected||applying)return;var n=new Date().getTime();if(n-lastStrokeSend>130){lastStrokeSend=n;localStroke(false)}},false);b.addEventListener('touchend',function(){setTimeout(function(){localStroke(true)},0)},false);window.addEventListener('mousemove',function(){if(!connected||applying)return;var n=new Date().getTime();if(n-lastStrokeSend>130){lastStrokeSend=n;localStroke(false)}},false);window.addEventListener('mouseup',function(){setTimeout(function(){localStroke(true)},0)},false);document.addEventListener('click',onUiEvent,false);document.addEventListener('change',onUiEvent,false);
document.getElementById('syncBtn').onclick=openPanel;document.getElementById('quickSyncBtn').onclick=openPanel;document.getElementById('syncClose').onclick=closePanel;document.getElementById('syncGenerateBtn').onclick=function(){roomInput.value=randomCode();room=clean(roomInput.value);updateUi()};document.getElementById('syncCreateBtn').onclick=createRoom;document.getElementById('syncJoinBtn').onclick=joinRoom;document.getElementById('syncLeaveBtn').onclick=closeAll;document.getElementById('syncCopyCodeBtn').onclick=copyCode;document.getElementById('syncShareBtn').onclick=share;adminEl.onchange=function(){adminMode=this.value==='all'?'all':'creator';if(connected&&role==='host'){send({type:'permissions',adminMode:adminMode});broadcastPresence()}updateUi()};
function initLink(){var m=(location.search||'').match(/[?&]room=([^&]+)/i);if(!m)return;var c=clean(decodeURIComponent(m[1]));if(!c)return;roomInput.value=c;setTimeout(function(){openPanel();joinRoom()},900)}
support();updateUi();initLink();
})();
